yay -Syu \
    --needed \
    --removemake \
    --answerclean y \
    --answerupgrade y \
    --answerdiff n \
    --answeredit n \
    arandr \
    arch-audit \
    aspnet-runtime \
    aur/android-emulator \
    aur/azure-cli \
    aur/jetbrains-toolbox \
    aur/nvm \
    aur/snapd \
    aur/spotify \
    aur/yay \
    aur/mongodb-compass \
    aur/webtorrent-desktop-bin \
    bluez \
    bluez-tools \
    bluez-utils \
    brightnessctl \
    cbatticon \
    cheese \
    chromium \
    cifs-utils \
    code \
    compton \
    curl \
    deluge \
    discord \
    docker \
    dotnet-host \
    dotnet-runtime \
    dotnet-sdk \
    dunst \
    efibootmgr \
    feh \
    fish \
    freerdp \
    fzf \
    gimp \
    git \
    glances \
    gparted \
    gufw \
    htop \
    i3-gaps \
    i3lock \
    i3status \
    imagemagick \
    lastpass-cli \
    lib32-nvidia-utils \
    lib32-vulkan-icd-loader \
    libreoffice \
    lm_sensors \
    lutris \
    neofetch \
    network-manager-applet \
    networkmanager \
    networkmanager-openvpn \
    networkmanager-pptp \
    nitrogen \
    nm-connection-editor \
    nodejs \
    npm \
    ntfs-3g \
    nvidia \
    nvidia-settings \
    nvidia-utils \
    obs-studio \
    opencl-nvidia \
    openssh \
    pacman-contrib \
    pacman-contrib \
    pacman-mirrorlist \
    pamixer \
    paprefs \
    pasystray \
    pavucontrol \
    polkit \
    polkit-gnome \
    pulseaudio \
    pulseaudio-alsa \
    pulseaudio-bluetooth \
    pulseaudio-jack \
    pulseeffects \
    qt5ct \
    redshift \
    remmina \
    rofi \
    rsync \
    rxvt-unicode \
    s-tui \
    scrot \
    speedtest-cli \
    steam \
    steam-native-runtime \
    thunar \
    tk \
    transmission-cli \
    transmission-gtk \
    ttf-fira-code \
    ttf-font-awesome \
    tumbler \
    viewnior \
    vlc \
    vulkan-icd-loader \
    wget \
    xclip \
    xdotool \
    xorg \
    xorg-apps \
    xorg-xbacklight \
    xorg-xinit \
    yarn \
